service: chef-roaster
useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-python-requirements

provider:
  name: aws
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      statements:
        - Effect: "Allow"
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
            - s3:*
            - dynamodb:*
          Resource: "*"
  runtime: python3.10
  stage: prod
  memorySize: 768
  timeout: 30
  region: eu-west-1
  lambdaHashingVersion: 20201221
  stackTags:
    owner: "Soheil Sheybani"
    project: "automation"

custom:
  pythonRequirements:
    dockerizePip: non-linux
  warmup:
    default:
      enabled: true
      events:
        - schedule: rate(5 minutes)
      prewarm: true

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**

functions:
  app:
    handler: src/main.lambda_handler
    events:
      - http:
          cors: true
          method: ANY
          path: /{proxy+}
      - http:
          cors: true
          method: ANY
          path: /
    environment:
      BUCKET_NAME: chef-roaster