name: "Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640721796322:role/GithubCIRole
          aws-region: eu-west-1

      - name: Use Node.js v18.20.5
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.5

      - run: npm ci

      - name: install serverless
        run: npm i -g serverless@3

      - name: install poetry
        run: pip install poetry

      - name: serverless deploy
        run: sls deploy --verbose
