name: "Deploy"

on:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640721796322:role/GithubCIRole
          aws-region: eu-west-1

      - name: Log in to Amazon ECR
        id: ecr_login
        run: |
          aws ecr get-login-password --region eu-west-1 |\
           docker login --username AWS\
            --password-stdin 640721796322.dkr.ecr.eu-west-1.amazonaws.com
        env:
          AWS_REGION: eu-west-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and use a new builder instance
        run: |
          docker buildx create --name mybuilder --use

      - uses: cachix/install-nix-action@v26
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run build-ii-services
        run: devenv shell build-ii-services

      - name: Run build-notion-api
        run: devenv shell build-notion-api

      - name: Deploy Serverless
        run: devenv shell npm run deploy
